[package]
name = "android-keyring"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[features]
default = []
compile_tests = []

[dependencies]
android_log-sys = "0.3.2"
base64 = "0.22.1"
jni = "0.21.1"
keyring = "=4.0.0-rc.1"
thiserror = "2.0.12"
